version: '2.1'
services:

  gateway:
      build : gateway/.
      image : gateway
      restart : always
      ports :
          - 10000:10000
      links:
          - registry
      logging:
            options:
              max-size: "10m"
              max-file: "10"

  payment-mongodb:
    environment:
        MONGODB_PASSWORD: user
    build : mongodb/.
    image : mongodb-micro
    restart: always
    ports:
          - 27017:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
      environment:
          MONGODB_PASSWORD: user
      build : mongodb/.
      image : mongodb-auth
      restart: always
      ports:
            - 27015:27017
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  payment-sender:
          build : payment-sender/.
          image : payment-sender
          restart: always
          ports:
                - 9000:9000
          links:
                - payment-mongodb
                - registry
          logging:
            options:
              max-size: "10m"
              max-file: "10"

  notification-mongodb:
      environment:
          MONGODB_PASSWORD: user
      build : mongodb/.
      image : mongodb-notification
      restart: always
      ports:
            - 27016:27017
      logging:
        options:
          max-size: "10m"
          max-file: "10"


  notification-service:
            build : notification-service/.
            image : notification-service
            restart: always
            ports:
                  - 7000:7000
            links:
                  - notification-mongodb
                  - registry
            logging:
              options:
                max-size: "10m"
                max-file: "10"
  registry:
      build : registry/.
      image: registry
      restart: always
      ports:
        - 8761:8761
      logging:
        options:
          max-size: "10m"
          max-file: "10"